language: node_js
node_js:
  - '8'

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

yarn: true

env:
  global:
    - JOBS=1

stages:
  - 'Tests'
  - 'Additional Tests'
  - 'Canary Tests'
  - name: 'Deploy'
    if: branch = master AND type = push

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
  include:
    - stage: 'Tests'
      name: 'Tests'
      install:
        - yarn install --non-interactive
      script:
        - yarn lint:js
        - ember test

    - name: 'Floating Dependencies'
      script:
        - ember test

    - stage: Additional Tests
      env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

    - stage: 'Canary Tests'
      script:
        - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
      env: EMBER_TRY_SCENARIO=ember-canary

    - stage: 'Deploy'
      name: 'Publish to npm'
      install:
        - yarn install --non-interactive
      script: yarn semantic-release

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox

script:
  - yarn lint:js
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
