language: node_js
node_js:
- '6'
dist: trusty
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  yarn: true
env:
- EMBER_TRY_SCENARIO=ember-lts-2.4
- EMBER_TRY_SCENARIO=ember-lts-2.8
- EMBER_TRY_SCENARIO=ember-release
- EMBER_TRY_SCENARIO=ember-beta
- EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- yarn global add phantomjs-prebuilt
- yarn global add greenkeeper-lockfile@1
- phantomjs --version
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
install:
- yarn install --no-lockfile
script:
- node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
deploy:
  provider: heroku
  api_key:
    secure: av1CAV8pjgrJhmKgkn5DwxPBTpQiTFcJBRMd9UPigNnwg6ljSES15E+mWnSesf3Lq0wfyd9pJx3Q73mILHHzVxivmcZS9RVN571ZkvjbUtN+Kd61GXO8Ls9UZmIsZpXuNiGvUi3VzBAb9k8kN4RZp6HSaSG3C+kdgzCxs+LNW0EipFgZdJu+8JVfno/WFFpiwQHhzRTZ1NqYI1ZFx84XQ1hMaKDUYN88XmIbeyaOkO7Yw+MtE0v46720CYBDm0EC9MrWXbXKP1OGYH5ltl5Eo0Bv5TZ7j40S213u/VdSDxEaoMe80r2FXs5vk5v/LV351PPj+IcL0m36Zsw34kekAXgRUKzdpLllf0UBg3s+sijvckKjU12cz+Fz8ABvVh8HnXGjB/fc7kcX3hFEjLzILutdK/ldjqA8I4A00uSinH+zSWu7oSR7QM0QxbmeLIHtVYCqQH0L1HgBxid5lWW4WhRdPoWXcCjQmeKRA2QbscRnAFBuzrBvPNGTrJEjxOgzYVY9TktSbFzopdnFMAdgKMud+xcfYyQzmB6uOuRdwWjx8l8Gm0KZ5nkYAdlO6bQPBYJIpsbTj5lS9b5eIqC7z64xBL0kIEFmo7ZqR5PbJFTgqnTHayycOzOFSS3HZ1Q9NoKApcZ+u8apnuUETxh5q9gcMufEbg4C15JHePrXJCo=
  app: ember-pin
  on:
    repo: mike-north/ember-pin
